"""empty message

Revision ID: 1031b4b39293
Revises: 7fb8374561ef
Create Date: 2024-07-08 13:58:36.074248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1031b4b39293'
down_revision = '7fb8374561ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Book', 'isbn',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'Borrows', 'Book', ['isbn'], ['isbn'])
    op.create_foreign_key(None, 'Borrows', 'User', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Borrows', type_='foreignkey')
    op.drop_constraint(None, 'Borrows', type_='foreignkey')
    op.alter_column('Book', 'isbn',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
