"""empty message

Revision ID: 42ba14853109
Revises: 1031b4b39293
Create Date: 2024-07-08 15:37:42.287585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ba14853109'
down_revision = '1031b4b39293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'token')
    # ### end Alembic commands ###
