"""empty message

Revision ID: 7fb8374561ef
Revises: 88c35d80b9a4
Create Date: 2024-07-08 13:52:00.300439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb8374561ef'
down_revision = '88c35d80b9a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Book', ['isbn'])
    op.create_foreign_key(None, 'Borrows', 'Book', ['isbn'], ['isbn'])
    op.create_foreign_key(None, 'Borrows', 'User', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Borrows', type_='foreignkey')
    op.drop_constraint(None, 'Borrows', type_='foreignkey')
    op.drop_constraint(None, 'Book', type_='unique')
    # ### end Alembic commands ###
