"""empty message

Revision ID: 833cb4369ff4
Revises: 76fa4fb14cfd
Create Date: 2024-07-08 13:09:10.311227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833cb4369ff4'
down_revision = '76fa4fb14cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Book',
    sa.Column('isbn', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('copies', sa.Integer(), nullable=True),
    sa.Column('available', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('isbn'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('Borrows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True, foreign_key=True),
    sa.Column('isbn', sa.String(), nullable=True, foreign_key=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('Borrows')
    op.drop_table('Book')
    # ### end Alembic commands ###
